version: '3.7'

services:
  postgres:
    image: debezium/postgres:12-alpine
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=pgsync
      - POSTGRES_DB=airbnb
      - POSTGRES_PASSWORD=PLEASE_REPLACE_ME
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U pgsync -d airbnb"]
      interval: 10s
      timeout: 5s
      retries: 5 
  redis:
    image: redis
    command: redis-server --requirepass PLEASE_REPLACE_ME
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    ports:
      - "9201:9200"
      - "9301:9300"
    environment:
      - xpack.security.enabled=false
      - network.host=127.0.0.1
      - http.host=0.0.0.0
  pgsync:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      org.label-schema.name: "pgsync"
      org.label-schema.description: "Postgres to elasticsearch sync"
      com.label-schema.service-type: "daemon"
    depends_on:
      - postgres
      - redis
      - elasticsearch
    environment:
      - PG_USER=pgsync
      - PG_HOST=postgres
      - PG_PASSWORD=PLEASE_REPLACE_ME
      - ELASTICSEARCH_PORT=9200
      - ELASTICSEARCH_SCHEME=http
      - ELASTICSEARCH_HOST=elasticsearch
      - REDIS_HOST=redis
      - REDIS_AUTH=PLEASE_REPLACE_ME

